### ISSUE TITLE
getting ENOENT: no such file or directory on install

### ISSUE THREAD

**Issue by aphusion** [mlazarov/bunyan-stackdriver#10]
Whenever I try to install this module I keep getting the following output, any ideas?- 
Vagrant Ubuntu 16.04

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bunyan-stackdriver"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path /vagrant/test/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/test/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/test/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/test/npm-debug.log

**Comment by zbjornson** [comment]
You might try deleting your node_modules directory and trying again. NPM is trying to install precompiled gRPC binaries and it looks like something went wrong in that process.

**Comment by aphusion** [comment]
hmm I can get it installed on Mac OSX no problem but on a vagrant box (Ubuntu 16.04) a clean install gives the same error

**Comment by aphusion** [comment]
I downgraded my Node version to 4.6.2 and it worked!

It failed on 6.9.0 and 6.10.0
