### ISSUE TITLE
Use credentials instead of keyFileName

### ISSUE THREAD

**Issue by stankud** [mlazarov/bunyan-stackdriver#2]
Would it be hard to add ability to pass in credentials option as an alternative to keyFileName. I see that it's possible in google-cloud-node repo, but it maybe only be available for authenticating on a global basis: https://github.com/GoogleCloudPlatform/google-cloud-node#authentication

**Comment by zbjornson** [comment]
By passing "credentials" you mean passing what the contents of the keyFile would be?

**Comment by zbjornson** [comment]
(Assuming that -- yes, it would be a trivial change.)

**Comment by stankud** [comment]
I can send a PR if that's ok.

**Comment by stankud** [comment]
PR: https://github.com/mlazarov/bunyan-stackdriver/pull/3

**Comment by mlazarov** [comment]
Request merged. Npm package published. @stankud ❤️
